const data = [
    {
        id: 0,
        name: "Motorbike",
        image: "https://www.drivingtests.co.nz/resources/wp-content/uploads/2022/04/motorbike-rider-on-country-road.jpg",
        alt: "Green Motorbike driving fast on a road",
        type: "Motorbike",
        make: "Yamaha",
        safetyRating: 3,
        rating: 1,
        rentPerDay: 109,
        minPeople: 1,
        maxPeople: 1,
        minDays: 1,
        maxDays: 5,
        lpkm: 3.7
    },
    {
        id: 1,
        name: "Small Car",
        image: "https://i1.pickpik.com/photos/979/201/100/automobile-automotive-blue-car-preview.jpg",
        alt: "Blue Small Car parked",
        type: "Small Car",
        make: "Ford",
        safetyRating: 1,
        rating: 4,
        rentPerDay: 129,
        minPeople: 1,
        maxPeople: 2,
        minDays: 1,
        maxDays: 10,
        lpkm: 8.5
    },
    {
        id: 2,
        name: "Large Car",
        image: "https://p1.pxfuel.com/preview/438/818/552/car-vehicle-gray-park.jpg",
        alt: "Grey Car parked facing the camera",
        type: "Large Car",
        make: "Toyota",
        safetyRating: 5,
        rating: 2,
        rentPerDay: 144,
        minPeople: 1,
        maxPeople: 5,
        minDays: 3,
        maxDays: 10,
        lpkm: 9.7
    },
    {
        id: 3,
        name: "Motorhome",
        image: "https://p1.pxfuel.com/preview/401/696/22/mobil-home-vehicle-transport-travel.jpg",
        alt: "Motorhome parked with the ocean in the background",
        type: "Motorhome",
        make: "Winnebago",
        safetyRating: 3,
        rating: 1,
        rentPerDay: 200,
        minPeople: 2,
        maxPeople: 6,
        minDays: 2,
        maxDays: 15,
        lpkm: 17
    }
]